### PR TITLE
Merge develop branch to master for tableberg v0.2

### PR DESCRIPTION
**Pull request by permafrost06**
Features added:
1. Added plugin page with instructions, documentation, and support.
2. Added table block preview.
3. (Table Block) Add custom logo.
4. (Table Block) Added block transform: transform core block into tableberg block.
5. (Table Block) Add table alignment control to toolbar.
6. (Table Block) Added global font style controls: Text Color, Link Color, Font Size.
7. (Button Block) Add gradient support.

Fixes:
1. Decreased initial spacing
2. Changed block name from "Tableberg Image" to "Image".
3. (Table Block) Fixed an issue with table footer toggle.
4. (Table Block) Show block toolbar when add table placeholder dialog is shown.
5. (Table Block) Fixed an issue with adding a new row.
6. (Table Block) Fixed an issue with undoing adding a row.
7. (Table Block) Fixed an issue with undoing adding a column.
8. (Button Block) Fixed an issue with color.

Coding changes:
1. Fix most typescript issues: add missing types, fix existing, add type declaration file.
2. Add `.DS_Store` files to `gitignore`.
3. Add freemius integration.
4. Update wp.org description (`readme.txt` and `tableberg.php`).
5. Add `build` directory to `gitignore`.
6. Remove unnecessary async/await.
7. Use hooks instead of functions where applicable.
8. Fix export script.
9. Add custom webpack config.

### CODE REVIEW

**Comment by permafrost06** [comment]
@farhan-shafi please let us know if we need to bump versions in the [`Assets.php`](https://github.com/DotCamp/tableberg/blob/develop/includes/Assets.php) file as well.

**Comment by imtiazrayhan** [comment]
> @farhan-shafi please let us know if we need to bump versions in the [`Assets.php`](https://github.com/DotCamp/tableberg/blob/develop/includes/Assets.php) file as well.

Yes, we have to. That ensures the latest files are loaded instead of the cached ones.

**Comment by farhan-shafi** [comment]
@permafrost06 Sorry for the late reply. Update the `TABLEBERG_VERSION` variable in the main `tableberg.php` and use it everywhere using version.

**Comment by permafrost06** [comment]
> @permafrost06 Sorry for the late reply. Update the `TABLEBERG_VERSION` variable in the main `tableberg.php` and use it everywhere using version.

This seems like a better solution. We’ll use this for future releases.

**Pull request merged**
